name: moviehub
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  dio: ^5.4.0
  permission_handler: ^11.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  better_player_enhanced: ^1.0.1
  video_player: ^2.8.1
  webview_flutter: ^4.4.2
  package_info_plus: ^9.0.0
  open_filex: ^4.5.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  workmanager: ^0.9.0+3
  share_plus: ^10.1.4
  introduction_screen: ^3.1.12
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/moviehub_app_icon_1770564869942.jpg"
  min_sdk_android: 21
